#!/bin/sh
# File generated by ocamlbuild

cd /home/zmurta/eclipse-workspace/Project1v1

rm -f Shape.cmi
rm -f Shape.cmo
# Also clean the script itself
rm -f /home/zmurta/eclipse-workspace/Project1v1/_build/sanitize.sh
